
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

    jpa:
      generate-ddl: true
      hibernate:
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: update

mail:
  host: smtp.gmail.com
  port: 587
  username: kdew0308@gmail.com
  password: icoyvbtzhcktmrzc
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

logging:
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mybatis/**/*.xml
